### PR TITLE
added company name #1

### PR DESCRIPTION
**Pull request by DPirate28**
added company name to the h1 as it was requested.

### CODE REVIEW

**Review by datapirate28 — COMMENTED** [review]
Can you please add an hashtag sign the title as well. Ex: #AfghanDevelopers

**Comment by DPirate28** [comment]
Sure. I got this.

**Review by datapirate28 — CHANGES_REQUESTED** [review]
Please make the changes as requested in the review above. Thanks!

**Review by datapirate28 — APPROVED** [review]
Great work! Thanks for all your hard work buddy. You can merge it.

**Pull request merged**
